pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'CheckEngine'
include 'core', 'cli', 'mod', 'early', 'early-test', 'forge-mod', 'mod-26', 'early-26', 'early-test-26'
