modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Uanme37/CheckEngine/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="checkengine_logo.png"
displayURL="https://github.com/Uanme37/CheckEngine"
authors="Guiltypotato"
description='''
Checks your modpack before you launch it: finds broken, missing and duplicate mods and explains them in plain English. No gameplay changes.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
