modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Uanme37/PackDoctor/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Guiltypotato"
description='''
Tells pack makers what's broken in their pack, in plain English. No gameplay changes.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
